---
CORE_EDGE_ROUTER:
  username: admin
  password: admin
  platform: cisco_xr
  port: 22
  connection_options:
    napalm:
      platform: iosxr
      username: admin
      password: admin
    netmiko:
      extras:
        timeout: 4
  data:
    nso:
      authgroup: labadmin
      protocol: ssh
      ned_id: cisco-iosxr-cli-3.5:cisco-iosxr-cli-3.5
      verification: none
XR:
  data: nothing
