---
CORE_EDGE_ROUTER:
  username: admin
  password: admin
  platform: cisco_xr
  port: 22
  connection_options:
    napalm:
      platform: cisco_xr
      username: cisco
      extras:
        optional_args:
          alt_host_keys: true
          # key_file: ~/.ssh/id_rsa
          alt_key_file: /home/cisco/.ssh/id_rsa
          use_keys: true
    netmiko:
      extras:
        timeout: 4
  data:
    nso:
      authgroup: labadmin
      protocol: ssh
      ned_id: cisco-iosxr-cli-3.5:cisco-iosxr-cli-3.5
      verification: none
XR:
  data: nothing
